version: "3"

networks:
  sspanel:

volumes:
  mysql_data:

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d
      - .:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - sspanel
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
      MYSQL_DATABASE: sspanel
    volumes:
      - ./configs/mysqld/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - sspanel
  web:
    container_name: web
    restart: always
    image: ehco1996/django-sspanel:runtime
    environment:
      MYSQL_PASSWORD: yourpass
      MYSQL_HOST: mysql
      DJANGO_ENV: production
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - sspanel
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: uwsgi uwsgi.ini
  # 定时任务
  cron:
    container_name: cron
    restart: always
    image: ehco1996/django-sspanel:runtime
    environment:
      MYSQL_PASSWORD: yourpass
      MYSQL_HOST: mysql
      DJANGO_ENV: production
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - web
    networks:
      - sspanel
    working_dir: /usr/src/app
    command:
      [
        "/bin/sh",
        "-c",
        "crond && python manage.py crontab add && tail -f logs/cron.log",
      ]
