version: "3"

networks:
  sspanel:

volumes:
  mysql_data:
  redis_aof:

services:
  nginx:
    image: nginx:1.20.1
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    restart: always
    container_name: nginx
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d
      - .:/usr/src/app
    ports:
      - ${port:-80}:80
    depends_on:
      - web
    networks:
      - sspanel
  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-yourpass}
      MYSQL_DATABASE: sspanel
    volumes:
      - ./configs/mysqld/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - sspanel
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    volumes:
      - redis_aof:/var/data/redis
    networks:
      - sspanel
  web:
    container_name: web
    restart: always
    image: ehco1996/django-sspanel:runtime
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-yourpass}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      DJANGO_ENV: ${DJANGO_ENV:-production}
      TZ: ${TZ:-Asia/Shanghai}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - redis
    networks:
      - sspanel
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: uwsgi uwsgi.ini
  celery-worker:
    container_name: celery-worker
    restart: always
    image: ehco1996/django-sspanel:runtime
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-yourpass}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      DJANGO_ENV: ${DJANGO_ENV:-production}
      TZ: ${TZ:-Asia/Shanghai}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - redis
    networks:
      - sspanel
    working_dir: /usr/src/app
    command:
      - celery
      - -A
      - apps
      - worker
      - -l
      - info
  # 定时任务
  celery-beat:
    container_name: celery-beat
    restart: always
    image: ehco1996/django-sspanel:runtime
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-yourpass}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      DJANGO_ENV: ${DJANGO_ENV:-production}
      TZ: ${TZ:-Asia/Shanghai}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - redis
    networks:
      - sspanel
    working_dir: /usr/src/app
    command:
      - celery
      - -A
      - apps
      - beat
      - -l
      - info
